export const DUMMY_EBOOKS = [
  {
    _id: "ebook_01",
    title: "Reborn in the Iron Citadel",
    writerId: { _id: "w1", name: "Kaito Maren" },
    genre: "Isekai",
    price: 4.99,
    coverImageUrl: "",
    format: "serialized",
    status: "published",
    featured: true,
    totalChapters: 38,
    purchaseCount: 1240,
    ratingAvg: 4.7,
  },
  {
    _id: "ebook_02",
    title: "Café at the Edge of Everything",
    writerId: { _id: "w2", name: "Lila Song" },
    genre: "Slice of Life",
    price: 2.99,
    coverImageUrl: "",
    format: "single",
    status: "published",
    featured: true,
    totalChapters: 1,
    purchaseCount: 870,
    ratingAvg: 4.9,
  },
  {
    _id: "ebook_03",
    title: "The Hollow Crown Prophecy",
    writerId: { _id: "w3", name: "Amir Noel" },
    genre: "Fantasy",
    price: 5.99,
    coverImageUrl: "",
    format: "serialized",
    status: "published",
    featured: true,
    totalChapters: 52,
    purchaseCount: 2100,
    ratingAvg: 4.6,
  },
  {
    _id: "ebook_04",
    title: "Between Two Moons",
    writerId: { _id: "w2", name: "Lila Song" },
    genre: "Romance",
    price: 3.49,
    coverImageUrl: "",
    format: "single",
    status: "published",
    featured: true,
    totalChapters: 1,
    purchaseCount: 560,
    ratingAvg: 4.5,
  },
  {
    _id: "ebook_05",
    title: "Signal Zero",
    writerId: { _id: "w4", name: "Priya Voss" },
    genre: "Thriller",
    price: 4.49,
    coverImageUrl: "",
    format: "serialized",
    status: "published",
    featured: true,
    totalChapters: 29,
    purchaseCount: 980,
    ratingAvg: 4.4,
  },
  {
    _id: "ebook_06",
    title: "A Witch's Quiet Town",
    writerId: { _id: "w1", name: "Kaito Maren" },
    genre: "Fantasy",
    price: 3.99,
    coverImageUrl: "",
    format: "serialized",
    status: "published",
    featured: false,
    totalChapters: 18,
    purchaseCount: 430,
    ratingAvg: 4.3,
  },
];

export const DUMMY_TOP_WRITERS = [
  {
    _id: "w3",
    name: "Amir Noel",
    avatarUrl: "https://i.pravatar.cc/150?u=amirnoel",
    bio: "Epic fantasy writer from Cairo. Obsessed with prophecy arcs and morally grey kings.",
    totalEbooks: 7,
    totalSales: 2100,
  },
  {
    _id: "w1",
    name: "Kaito Maren",
    avatarUrl: "https://i.pravatar.cc/150?u=kaitomaren",
    bio: "Writes isekai and cozy magic. Believes every portal fantasy needs a good meal scene.",
    totalEbooks: 5,
    totalSales: 1670,
  },
  {
    _id: "w2",
    name: "Lila Song",
    avatarUrl: "https://i.pravatar.cc/150?u=lilasong",
    bio: "Slice-of-life and romance. Chronic overpacker, writes best at 2am.",
    totalEbooks: 4,
    totalSales: 1430,
  },
];